---
title: "gmin figures"
author: "Remko Duursma"
date: "1 August 2017"
output: 
  html_document:
    theme: flatly
---


```{r}
source("R/load.R")
pacman::p_load(magicaxis)
```


```{r}
v <- gmindat$gmin
hist(v, breaks=30, xlim=c(0,40), main="", freq=FALSE,
     ylim=c(0,0.15),
     col="lightgrey",
     xlab=expression(g[min]~~(mmol~m^-2~s^-1)))
curve(dlnorm(x, mean(log(v)), sd=sd(log(v))), add=TRUE,
      n=501)
```

```{r}
v <- log10(gmindat$gmin)
par(yaxs="i", mgp=c(3,1,0), cex.lab=1.2)
hist(v, breaks=30, main="", freq=FALSE,
     #ylim=c(0,0.15),
     xlim=c(-1,2),
     col="lightgrey",
     axes=FALSE,
     xlab=expression(g[min]~~(mmol~m^-2~s^-1)))
magaxis(side=1, unlog=1, usepar=TRUE)
axis(2)
curve(dnorm(x, mean=mean(v), sd=sd(v)), add=TRUE,
      n=101)

```



```{r, fig.cap="Figure 1.", fig.width=6, fig.height=6}
figure_sim()
```


```{r, fig.width=9, fig.height=4}
figure_R2g0(lin2015coef, miner)
```


```{r, fig.width=5, fig.height=5}
figure_gmin_review_2(gdfr)
```

```{r, fig.width=3, fig.height=4}
figure_gmin_bygroup(gmindat)
```

```{r, fig.width=3.5, fig.height=4 }
figure_wtc4_gmin_2(wtc4gmin)
```

```{r, fig.width=6, fig.height=5}
figure_hakea_gmin(lopw)
```


```{r, fig.width=6, fig.height=5}
gmin_by_family(gmindat)
```

```{r, fig.width=6, fig.height=5}
gmin_by_order(gmindat)
```


